all:
	gcc -O3 driveGillespie.c -o gillespie.out -lm

	chmod a+x batchGillespie.sh

run:
	gcc -O3 driveGillespie.c -o gillespie.out -lm

	chmod a+x batchGillespie_Control.sh

	./batchGillespie_Control.sh 7 v



