all:
	gcc -O3 driveGillespie.c -o gillespie.out -lm

run:
	gcc -O3 driveGillespie.c -o gillespie.out -lm

	./gillespie.out transitionMatrixMultipleTestBoundLigands.cat.txt 6 2 testGillespieOutput.txt 1



