all:
	gcc -O3 driveGillespie.c -o gillespie.out -lm

run:
	gcc -O3 driveGillespie.c -o gillespie.out -lm

	./gillespie.out transitionMatrixMultipleTestBoundLigands.cat.txt 6 20000000 GillespieMultipleTestBoundLigandsAllData.txt GillespieMultipleTestBoundLigandsTop50.txt



