all:
	gcc -O3 driveMetropolis.c -o metropolis.out -lm


batch:
	gcc -O3 driveMetropolis.c -o metropolis.out -lm

	chmod a+x batchMetropolis.sh

	cp metropolis.out ~/Documents/polymer-c_runs/.

run:

	gcc -O3 driveMetropolis.c -o metropolis.out -lm

	chmod a+x batchMetropolis.sh

	./batchMetropolis.sh 7 v


